### ISSUE TITLE
Problem while using doctrine/orm v. 2.4.5 and doctrine/mongodb-odm-bundle v 4.0.0

### ISSUE THREAD

**Issue by dyshlenko** [markitosgv/JWTRefreshTokenBundle#174]
In my project (Symfony 4.3, PHP 7.3, `api-platform/core v2.5.0`, `api-platform/api-pack v1.2.0`), I use `doctrine/orm v2.4.5` to access an existing user database and `doctrine/mongodb-odm-bundle v4.0.0`, `doctrine/mongodb-odm v2.0.1` to work with the project database. Authorization is based on the lexik/jwt-authentication-bundle package and works fine.

When I try to install `gesdinet/jwt-refresh-token-bundle`, I get a broken system in which even the `bin/console` command crashes with an error. This is visible even in composer messages:

```
vagrant@homestead:~/code/meta_editor_api$ composer require gesdinet/jwt-refresh-token-bundle
Using version ^0.8.2 for gesdinet/jwt-refresh-token-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Package operations: 1 install, 0 updates, 0 removals
  - Installing gesdinet/jwt-refresh-token-bundle (v0.8.2): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (12961e816cf16d8c55b1e11a67ca5c9f)
  - Configuring gesdinet/jwt-refresh-token-bundle (>=v0.8.2): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DocumentRepository" from namespace "Doctrine\ODM\MongoDB".
**!!  Did you forget a "use" statement for "Doctrine\ODM\MongoDB\Repository\DocumentRepository"? in /home/vagrant/code/meta_editor_api/vendor/gesdinet/jwt-refresh-token-bundle/Document/RefreshTokenRepository.php:16**
!!  Stack trace:
!!  #0 /home/vagrant/code/meta_editor_api/vendor/api-platform/core/src/Util/ReflectionClassRecursiveIterator.php(48): require_once()
!!  #1 /home/vagrant/code/meta_editor_api/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php(50): ApiPlatform\Core\Util\ReflectionClassRecursiveIterator::getReflectionClassesFromDirectories(Array)
!!  #2 /home/vagrant/code/meta_editor_api/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): ApiPlatform\Core\Bridge\Symfony\Bundle\DependencyInjection\Compiler\AnnotationFilterPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #3 /home/vag in /home/vagrant/code/meta_editor_api/vendor/gesdinet/jwt-refresh-token-bundle/Document/RefreshTokenRepository.php on line 16
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DocumentRepository" from namespace "Doctrine\ODM\MongoDB".
!!  Did you forget a "use" statement for "Doctrine\ODM\MongoDB\Repository\DocumentRepository"? in /home/vagrant/code/meta_editor_api/vendor/gesdinet/jwt-refresh-token-bundle/Document/RefreshTokenRepository.php:16
!!  Stack trace:
!!  #0 /home/vagrant/code/meta_editor_api/vendor/api-platform/core/src/Util/ReflectionClassRecursiveIterator.php(48): require_once()
!!  #1 /home/vagrant/code/meta_editor_api/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/Compiler/AnnotationFilterPass.php(50): ApiPlatform\Core\Util\ReflectionClassRecursiveIterator::getReflectionClassesFromDirectories(Array)
!!  #2 /home/vagrant/code/meta_editor_api/vendor/symfony/dependency-injection/Compiler/Compiler.php(94): ApiPlatform\Core\Bridge\Symfony\Bundle\DependencyInjection\Compiler\AnnotationFilterPass->process(Object(Symfony\Component\DependencyInjection\ContainerBuilder))
!!  #3 /home/vag in /home/vagrant/code/meta_editor_api/vendor/gesdinet/jwt-refresh-token-bundle/Document/RefreshTokenRepository.php on line 16
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.
```

vendor/gesdinet/jwt-refresh-token-bundle/Document/RefreshTokenRepository.php: 16 contains code designed to unify support for different versions of `doctrine/mongodb-odm`

```php
if (class_exists(MongoDBDocumentRepository::class)) {
    // Support for doctrine/mongodb-odm >= 2.0
    class BaseRepository extends MongoDBDocumentRepository
    {
    }
} else {
    // Support for doctrine/mongodb-odm < 2.0
    **class BaseRepository extends DocumentRepository**
    {
    }
}
```

I was hoping to use a table in MySQL to store the RefreshToken, but at present I can’t install the package without crashing the application - the code for the `class BaseRepository extends DocumentRepository` is called **always** and leads to an application error.

Is there any way to limit the autoload of the `Gesdinet\JWTRefreshTokenBundle\Document\RefreshTokenRepository` class when the Doctrine ORM is used to authenticate the user?

**Comment by shakaran** [comment]
@dyshlenko, you got no reply at all in six years. Sorry.

Your diagnosis was right: `Document/RefreshTokenRepository.php` carried a conditional to work with both MongoDB ODM 1.x and 2.x, where the parent class was only resolvable once that conditional had run. API Platform's `ReflectionClassRecursiveIterator` scans directories and `require_once`s the files it finds directly, so the class got loaded without the setup it depended on, and the parent was not there. Hence a fatal error during `cache:clear`, at install time, before you could do anything about it.

**It is gone.** ODM 1.x support was dropped in #284 (a73998f, v1.0.0), and the file is now an ordinary class:

```php
use Doctrine\ODM\MongoDB\Repository\DocumentRepository;

class RefreshTokenRepository extends DocumentRepository implements RefreshTokenRepositoryInterface, DeleteRefreshTokenRepositoryInterface
```

No conditional, nothing that has to run before it can be loaded, so a scanner that requires the file directly gets a normal class. `composer.json` also declares `conflict: doctrine/mongodb-odm <2.7`, so the incompatible combination cannot be installed rather than being discovered during a cache clear.

This is the same root as #169, which is still open and about the same conditional from the other side.

Closing this. The pattern that caused it — a class whose parent depends on code having run first — was the real problem, and it is not in the bundle any more.
